### ISSUE TITLE
A potential bug in JtsMultiPolyLineConverter

### ISSUE THREAD

**Issue by Karpinchyk** [osmlab/atlas#156]
We are getting a ClassCastException when trying to convert a MultiPolyLine to WKT.

Here is the stack trace:
```
Exception in thread "main" java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Lcom.vividsolutions.jts.geom.LineString;
	at org.openstreetmap.atlas.geography.converters.jts.JtsMultiPolyLineConverter.convert(JtsMultiPolyLineConverter.java:42)
	at org.openstreetmap.atlas.geography.converters.WktMultiPolyLineConverter.convert(WktMultiPolyLineConverter.java:39)
...
```

This fix in src/main/java/org/openstreetmap/atlas/geography/converters/jts/JtsMultiPolyLineConverter.java is working for us:

```
     private static final JtsCoordinateArrayConverter COORDINATE_ARRAY_CONVERTER = new JtsCoordinateArrayConverter();
+    private static final JtsPolyLineConverter POLYLINE_CONVERTER = new JtsPolyLineConverter();
     private static final GeometryFactory FACTORY = JtsPrecisionManager.getGeometryFactory();
 
     @Override
@@ -38,8 +43,10 @@ public class JtsMultiPolyLineConverter implements TwoWayConverter<MultiPolyLine,
     @Override
     public MultiLineString convert(final MultiPolyLine multiPolyLine)
     {
-        final LineString[] lineStrings = (LineString[]) ImmutableList
-                .copyOf(multiPolyLine.iterator()).toArray();
-        return new MultiLineString(lineStrings, FACTORY);
+        final List<LineString> lineStringList =
+            StreamSupport.stream(
+                    Spliterators.spliteratorUnknownSize(multiPolyLine.iterator(), Spliterator.ORDERED), false).
+                    map(pl -> POLYLINE_CONVERTER.convert(pl)).collect(Collectors.toList());
+        return new MultiLineString(lineStringList.toArray(new LineString[lineStringList.size()]), FACTORY);
     }
```

**Comment by MikeGost** [comment]
Can you open a PR with the fix? Two minor requests:

1. Can you add a test to the MultiPolyLineTest that converts the MultiPolyLine to WKT. 
2. Consider using the below simplification of your fix:

```
    @Override
    public MultiLineString convert(final MultiPolyLine multiPolyLine)
    {
        final List<LineString> lineStringList = Iterables.stream(multiPolyLine)
                .map(POLYLINE_CONVERTER::convert).collectToList();
        return new MultiLineString(lineStringList.toArray(new LineString[lineStringList.size()]),
                FACTORY);
    }
```

**Comment by MikeGost** [comment]
https://github.com/osmlab/atlas/pull/157
