### ISSUE TITLE
Command pbf2atlas creates corrupted atlas files

### ISSUE THREAD

**Issue by frostblooded** [osmlab/atlas#476]
## Problem

I am trying to use the command `pbf2atlas` to create an atlas file from a .osm.pbf file, but the resulting atlas file seems to be corrupted.

## What I did

I have downloaded the Belize file from [here](https://download.geofabrik.de/central-america.html). Then I ran the command `atlas pbf2atlas --countryName BLZ belize-latest.osm.pbf`. This gave me the file "BLZ_belize-latest.osm.atlas". Then I ran this code:

```
import org.openstreetmap.atlas.geography.atlas.Atlas;
import org.openstreetmap.atlas.geography.atlas.AtlasResourceLoader;
import org.openstreetmap.atlas.streaming.resource.File;

public class Main {
    public static void main(String[] args) {
        File atlasFile = new File("BGR_map.osm.atlas");
        Atlas atlas = new AtlasResourceLoader().load(atlasFile);
        atlas.nodes().forEach(System.out::println);
    }
}
```

,but it gives the following error:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" org.openstreetmap.atlas.exception.CoreException: MetaData not here!
	at org.openstreetmap.atlas.geography.atlas.packed.PackedAtlasSerializer.load(PackedAtlasSerializer.java:96)
	at org.openstreetmap.atlas.geography.atlas.packed.PackedAtlas.load(PackedAtlas.java:190)
	at org.openstreetmap.atlas.geography.atlas.AtlasResourceLoader.load(AtlasResourceLoader.java:73)
	at org.openstreetmap.atlas.geography.atlas.AtlasResourceLoader.load(AtlasResourceLoader.java:96)
	at Main.main(Main.java:8)
Caused by: org.openstreetmap.atlas.exception.CoreException: Unable to read Atlas field metaData
	at org.openstreetmap.atlas.geography.atlas.packed.PackedAtlasSerializer.deserializeIfNeeded(PackedAtlasSerializer.java:154)
	at org.openstreetmap.atlas.geography.atlas.packed.PackedAtlas.metaData(PackedAtlas.java:511)
	at org.openstreetmap.atlas.geography.atlas.packed.PackedAtlasSerializer.load(PackedAtlasSerializer.java:92)
	... 4 more
Caused by: org.openstreetmap.atlas.exception.CoreException: Could not load Field metaData from BLZ_belize-latest.osm.atlas
	at org.openstreetmap.atlas.geography.atlas.packed.PackedAtlasSerializer.deserializeResource(PackedAtlasSerializer.java:258)
	at org.openstreetmap.atlas.geography.atlas.packed.PackedAtlasSerializer.deserializeSingleField(PackedAtlasSerializer.java:275)
	at org.openstreetmap.atlas.geography.atlas.packed.PackedAtlasSerializer.load(PackedAtlasSerializer.java:344)
	at org.openstreetmap.atlas.geography.atlas.packed.PackedAtlasSerializer.deserializeIfNeeded(PackedAtlasSerializer.java:149)
	... 6 more
Caused by: java.io.StreamCorruptedException: invalid stream header: 08B98305
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:866)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:358)
	at org.openstreetmap.atlas.geography.atlas.packed.PackedAtlasSerializer.deserializeResource(PackedAtlasSerializer.java:247)
	... 9 more
```

On the other hand, if I create the atlas file with my own Java code, it works correctly afterwards and opens the file as it should. My code for building the file is:

```
import org.openstreetmap.atlas.geography.atlas.Atlas;
  	private static void buildAtlas() {
        File pbfFile = new File("belize-latest.osm.pbf");
        System.out.println("Loading raw atlas from PBF...");
        RawAtlasGenerator rawAtlasGenerator = new RawAtlasGenerator(pbfFile, AtlasLoadingOption.createOptionWithNoSlicing());
        System.out.println("Building atlas...");
        Atlas atlas = rawAtlasGenerator.build();
        System.out.println("Saving atlas...");
        atlas.save(new File("map.atlas"));
    }
```

## Version
`atlas-config list` says `atlas-a421a45`

There is also a short discussion about this problem [here](https://stackoverflow.com/questions/56414527/getting-atlas-files-to-use-with-osm-atlas?noredirect=1#comment99841949_56414527). At first I thought that I am doing something wrong, but maybe the issue is with the command itself.

**Comment by lucaspcram** [comment]
Hi @frostblooded. First of all, thanks for checking out `atlas` as well as the command line tools - we are very excited to have some community users! I am actually struggling to reproduce your issue. I am going to post a screenshot of some exact commands I ran, including some additional logging configuration which may be useful.

If you could run these commands and then send the resulting `output.log` file we may be able to narrow the issue. Also, please check the output of `java -version`. I would like to rule out an issue due to differing JDK versions.

<img width="1587" alt="Screen Shot 2019-07-01 at 10 07 55 AM" src="https://user-images.githubusercontent.com/8269882/60454926-fe70c780-9be9-11e9-9440-7dc4d5495d22.png">

**Comment by frostblooded** [comment]
The file that is opened in my snippet indeed has the wrong name for this example, but that is not the problem. It still doesn't work if I write the correct name and I have tried with different maps and names.

I tried everything that you said and you can see what the output was [here](https://ibb.co/HF8Q1dk).

Here is the [output file](https://gofile.io/?c=BHAzEk).

The java version that I am using is

```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.18.04.1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)
```
and I have confirmed that this is the Java version that is being used in my IntelliJ. We haven't changed anything, but I thought I should mention that the generated file still can't be opened.

**Comment by lucaspcram** [comment]
It's strange - I am still unable to reproduce this issue. I'm hoping this hasn't been blocking what you're trying to do.

**Comment by matthieun** [comment]
Please re-open if this still happens. I have tried many times with jdk 11+ and it works well.
